target-version = "py38"
line-length = 79

[lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "PT",
    "RUF100",
    "RUF012",
    "C901",
]
ignore = ["PT011"]

[lint.isort]
known-first-party = ["elsim"]

[lint.per-file-ignores]
"docs/conf.py" = ["E402"]

[lint.mccabe]
max-complexity = 10
